# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="bira"

plugins=(
    fzf
    gcloud
    git
    node
    npm
    yarn
)

source $ZSH/oh-my-zsh.sh

# add command-line fuzzy finder to zsh
source <(fzf --zsh)

# enable fzf to history [ ctrl + R ]
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# add git ssh key
@eval "$(ssh-agent -s)" 2>/dev/null
ssh-add ~/.ssh/id_ed25519 2>/dev/null


# TIPS
#
# Kill command with FZF
# ~$ kill -9 ** <TAB>